name: todo-list

services:
  flask:
    build: .
    container_name: todo_flask_app
    restart: always
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
